/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_flexcan.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define CAN3_PERIPHERAL CAN3
/* Definition of the clock source frequency */
#define CAN3_CLOCK_SOURCE 24000000UL
/* CAN3 interrupt vector ID (number). */
#define CAN3_FLEXCAN_IRQN CAN3_IRQn
/* CAN3 interrupt handler identifier. */
#define CAN3_FLEXCAN_IRQHANDLER CAN3_IRQHandler
/* CAN3 interrupt vector ID (number). */
#define CAN3_ERROR_IRQN CAN3_ERROR_IRQn
/* CAN3 interrupt handler identifier. */
#define CAN3_ERROR_IRQHANDLER CAN3_ERROR_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const flexcan_config_t CAN3_config;
/* Message buffer 0 configuration structure */
extern const flexcan_rx_mb_config_t CAN3_rx_mb_config_0;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
